//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.10.14 at 02:52:29 PM PDT
//

package com.openairmarket.etl.pipeline.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.openairmarket.etl.pipeline.model package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _Pipelines_QNAME =
      new QName("http://www.config.domain.pipeline.workday.corp.google.com", "pipelines");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.openairmarket.etl.pipeline.model
   */
  public ObjectFactory() {}

  /** Create an instance of {@link Pipelines } */
  public Pipelines createPipelines() {
    return new Pipelines();
  }

  /** Create an instance of {@link Extracts } */
  public Extracts createExtracts() {
    return new Extracts();
  }

  /** Create an instance of {@link Transformations } */
  public Transformations createTransformations() {
    return new Transformations();
  }

  /** Create an instance of {@link Validations } */
  public Validations createValidations() {
    return new Validations();
  }

  /** Create an instance of {@link Inputs } */
  public Inputs createInputs() {
    return new Inputs();
  }

  /** Create an instance of {@link PreValidations } */
  public PreValidations createPreValidations() {
    return new PreValidations();
  }

  /** Create an instance of {@link Conversions } */
  public Conversions createConversions() {
    return new Conversions();
  }

  /** Create an instance of {@link Identifier } */
  public Identifier createIdentifier() {
    return new Identifier();
  }

  /** Create an instance of {@link Extract } */
  public Extract createExtract() {
    return new Extract();
  }

  /** Create an instance of {@link PreValidation } */
  public PreValidation createPreValidation() {
    return new PreValidation();
  }

  /** Create an instance of {@link Input } */
  public Input createInput() {
    return new Input();
  }

  /** Create an instance of {@link Conversion } */
  public Conversion createConversion() {
    return new Conversion();
  }

  /** Create an instance of {@link Validation } */
  public Validation createValidation() {
    return new Validation();
  }

  /** Create an instance of {@link Scripts } */
  public Scripts createScripts() {
    return new Scripts();
  }

  /** Create an instance of {@link Script } */
  public Script createScript() {
    return new Script();
  }

  /** Create an instance of {@link Pipelines.Pipeline } */
  public Pipelines.Pipeline createPipelinesPipeline() {
    return new Pipelines.Pipeline();
  }

  /** Create an instance of {@link Pipelines.Extracts } */
  public Pipelines.Extracts createPipelinesExtracts() {
    return new Pipelines.Extracts();
  }

  /** Create an instance of {@link Pipelines.Inputs } */
  public Pipelines.Inputs createPipelinesInputs() {
    return new Pipelines.Inputs();
  }

  /** Create an instance of {@link Pipelines.PreValidations } */
  public Pipelines.PreValidations createPipelinesPreValidations() {
    return new Pipelines.PreValidations();
  }

  /** Create an instance of {@link Pipelines.Conversions } */
  public Pipelines.Conversions createPipelinesConversions() {
    return new Pipelines.Conversions();
  }

  /** Create an instance of {@link Pipelines.Validations } */
  public Pipelines.Validations createPipelinesValidations() {
    return new Pipelines.Validations();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Pipelines }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link Pipelines }{@code >}
   */
  @XmlElementDecl(
      namespace = "http://www.config.domain.pipeline.workday.corp.google.com",
      name = "pipelines")
  public JAXBElement<Pipelines> createPipelines(Pipelines value) {
    return new JAXBElement<Pipelines>(_Pipelines_QNAME, Pipelines.class, null, value);
  }
}
