//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.10.14 at 02:52:29 PM PDT
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://www.config.domain.pipeline.workday.corp.google.com",
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.openairmarket.etl.pipeline.model;
